config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get "about", to: "pages#about"
  get "home", to: "pages#home"
  get "date", to: "pages#date"
  get "recipi", to:"pages#recipi"
  get "foods/wwindex", to:"foods#wwindex"
  resources :foods, only: [:index, :show, :edit, :update, :new, :create, :destroy]
  get "foods/:when/:which", to: "foods#whenwhich"
  post "foods/:when/:which", to:"foods#wwcreate"
  get "users/all/:date", to:"users#allusersfoods"
  get "users/show2/:id", to:"users#show2"
  resources :users
  #ingredients
  get 'ingredients/index'
  get 'ingredients/show'
  get 'ingredients/:id/edit', to:"ingredients#edit"
  patch 'ingredients/:id', to:"ingredients#update"
  #post "users/new", to: 'users#create'
  get 'signup', to: 'users#new'
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'

  #unmatched route
  get '*unmatched_route', to: 'application#unmatched'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_one :ingredient, dependent: :destroy
  mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :food
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "ログインしてください！"
      redirect_to login_path
    end
  end
  def unmatched
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :require_user
  
  def whenwhich
    @food=Food.new
    @food.build_ingredient
    @which = params[:which]
    @when = params[:when].to_i
  end
  def wwindex
    @user=User.find(current_user.id)
  end
  def wwcreate
    @which = params[:which]
    @when = params[:when].to_i
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    @food.when = @when
    @food.which = @which
    @food.save
    redirect_to user_path(current_user.id)
  end
  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end
  def index
    @foods=Food.all
  end
  def new
    @food = Food.new
  end
  def create
    @which = params[:which]
    @when = params[:when].to_i
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    @food.save
    redirect_to user_path(current_user.id)
  end
  def edit
    @food = Food.find(params[:id]) 
  end
  def show 
    @food = Food.find(params[:id]) 
  end
  def update
    @food = Food.find(params[:id])
    @food.update(food_params)
    flash[:notice] = "食事内容が更新されました"
    redirect_to user_path(current_user.id)
  end
  private
  def food_params
    params.require(:food).permit(:description, :user_id, :image, :when, :which, ingredient_attributes: [:id, :cal, :food_id, :protein, :lipid, :carbon, :ca, :fe, :v_a, :v_e, :v_b1, :v_b2, :v_c, :fiber, :fatty, :saltval])
  end
end
  

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @hogehoge="ほげほげです。"
    @hogenum = 30
  end

  def show
    @ingredients=Ingredient.all
    @user4=[]
    @user5=[]
    @user6=[]
    @user7=[]
    @user8=[]
    (18..24).each do |num|
      @user4.concat([Food.where(user_id: 4).where(when: num).where(which: "dinner").last.ingredient])
      @user5.concat([Food.where(user_id: 5).where(when: num).where(which: "dinner").last.ingredient])
      @user6.concat([Food.where(user_id: 6).where(when: num).where(which: "dinner").last.ingredient])
      @user7.concat([Food.where(user_id: 7).where(when: num).where(which: "dinner").last.ingredient])
      @user8.concat([Food.where(user_id: 8).where(when: num).where(which: "dinner").last.ingredient])
    end
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      flash[:notice] = "ingredient was updated successfully."
      redirect_to "/foods"
    else
      render 'edit'
    end
  end
  private 
  def ingredient_params
    params.require(:ingredient).permit(:cal, :protein, :lipid, :carbon, :ca, :fe, :v_a, :v_e, :v_b1, :v_b2, :v_c, :fiber, :fatty, :saltval)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_user
  def home
  end
  def about
  end
  def date
  end
  def recipi
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new,:create]
  def index
    @users=User.all
  end
  def allusersfoods
    @date=params[:date]
    @users=User.all
  end
  def show
    @user=User.find(params[:id])
    @foods=[]
    (18..23).each do |num|
      @foods.concat([Food.where(user_id: @user.id).where(when: num).where(which: "breakfast").last])
      @foods.concat([Food.where(user_id: @user.id).where(when: num).where(which: "lunch").last])
      @foods.concat([Food.where(user_id: @user.id).where(when: num).where(which: "dinner").last])
    end
  end
  def show2
    @user=User.find(params[:id])
    @foods=[]
    (18..23).each do |num|
      @foods.concat([Food.where(user_id: @user.id).where(when: num).where(which: "breakfast").last])
      @foods.concat([Food.where(user_id: @user.id).where(when: num).where(which: "lunch").last])
      @foods.concat([Food.where(user_id: @user.id).where(when: num).where(which: "dinner").last])
    end
  end
  def new 
    @user=User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice]="Welcome to NoRooF #{@user.username}"
      session[:user_id] = @user.id
      redirect_to users_path
    else
      flash.now[:alert] = "エラー発生"
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User was updated successfully."
      redirect_to users_path
    else
      render 'edit'
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def whichfood(which)
    case which
      when "breakfast" then
        "朝食"
      when "lunch" then
        "昼食"
      when "dinner" then
        "夕食"
      end
  end
  def novdate(date)
    num = date %7
    if num== 0 then
      "(日)"
    elsif num==1 then
      "(月)"
    elsif num==2 then
      "(火)"
    elsif num==3 then
      "(水)"
    elsif num==4 then
      "(木)"
    elsif num==5 then
      "(金)"
    elsif num==6 then
      "(土)"
    end
  end
  def userstatus(user)
    if user.admin? then
      "管理者"
    elsif user.nut? then
      "管理栄養士"
    else
      "ユーザー"
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/unmatched.html.erb
<div class="container">URLエラー</div>

app/views/foods/edit.html.erb
<div class="container">
  <h2>食事内容を編集</h2>
  <h2>#<%= @food.id %></h2>
  <%= form_for(@food, url:{controller:'foods', action:'update'}) do |form| %>
    <div class="form-group">
      <label for="description">食事内容</label>
      <%= form.text_area :description, {class:"form-control", placeholder:"xxx cal",rows: 10} %>
      <label for="image">Image</label>
      <%= form.file_field :image %>
      <br>
    
    </div>
    <%= form.submit "アップデート" ,class:"btn btn-primary" %>
  <% end %>
  
  
</div>

app/views/foods/index.html.erb
<div class="container">
<h2 class="mb-5 mt-5">みんなの食事(投稿順)</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Username</th>
        <th scope="col">いつ</th>
        <th scope="col">食べたもの</th>
        <th scope="col">Image</th>
        <th scope="col">Handle</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <th scope="row"><%= food.id %></th>
          <td><%= food.user.username %></td>
          <td><%= food.when %>日<%= whichfood(food.which) %></td>
          <td><%= safe_join(food.description.split("\n"),tag(:br)) %></td>
          <td><% if food.image? %>
              <%= image_tag food.image.url , style:"max-width:10rem" %>
              <% else %>
              <%= image_tag "noimage.png" %>
              <% end %>
          </td>
          
          <td>
          <%= link_to "このユーザーの食事記録を見る", user_path(food.user) ,class:"btn btn-outline-success"%><br>
          <% if current_user.admin? %> 
            <%= link_to 'Edit', edit_food_path(food) %><br>
            <%= link_to 'Delete', food_path(food), method: :delete, data: { confirm: "Are you sure?" }%><br>
            <% if food.ingredient %>
              <%= link_to 'Ingredient' , "/ingredients/"+food.ingredient.id.to_s+"/edit" %>
            <% end %>
          <% end %>
          </td>
        </tr>
        <% # image_tag food.image.url if food.image? %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="container">
  <h2>Adding new member</h2>
  <%= form_for(@food, url:{controller:'foods', action:'create'}) do |form| %>
    <div class="form-group">
      <label for="username">description</label>
      <%= form.text_field :description,{class:"form-control", placeholder:"username"} %>
      
      <label for="user_id">User-id</label>
      <%= form.text_field :user_id,{class:"form-control", placeholder:"user_id"} %>
      
      <%= form.label :image, 'image' %>
      <%= form.file_field :image %>
    <%= form.submit "作成" , class:"btn btn-primary" %>
    
    </div>
  <% end %>
  
</div>

app/views/foods/show.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Handle</th>
      </tr>
    </thead>
    <tbody>
      
        <tr>
          <th scope="row"><%= @food.id %></th>
          <td><%= @food.description %></td>
          <td><%= @food.user_id %></td>
          <td><% if @food.image? %>
          <%= image_tag @food.image.url %>
        <% else %>
          <%= image_tag "https://via.placeholder.com/150" %>
        <% end %>
        </td>
        </tr>
    </tbody>
  </table>

</div>

app/views/foods/whenwhich.html.erb
<div class="container">
  <h2>食事を新規追加</h2>
  <p><%= @when %>日</p>
  <p><%= whichfood(@which) %></p>
  <div class="row justify-content-center">
  <%= render 'shared/errors', obj: @food %>
  
  <%= form_with(model: @food, url:{controller:'foods', action:'wwcreate'}, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
    <div class="form-group">
    <label for="user_id">食事内容</label>
      
        <%= f.text_area :description, class: "form-control shadow rounded", placeholder: "食事記録を入力してください" ,rows: 10%>
    </div>
    
      <%= f.label :image, 'image' %>
      <%= f.file_field :image %>
      <%= f.fields_for :ingredient do |i| %>
         <%= i.hidden_field :cal, value:0 %>
         <%= i.hidden_field :protein, value:0 %>
         <%= i.hidden_field :lipid, value:0 %>
         <%= i.hidden_field :carbon, value:0 %>
         <%= i.hidden_field :ca, value:0 %>
         <%= i.hidden_field :fe, value:0 %>
         <%= i.hidden_field :v_a, value:0 %>
         <%= i.hidden_field :v_e, value:0 %>
         <%= i.hidden_field :v_b1, value:0 %>
         <%= i.hidden_field :v_b2, value:0 %>
         <%= i.hidden_field :v_c, value:0 %>
         <%= i.hidden_field :fiber, value:0 %>
         <%= i.hidden_field :fatty, value:0 %>
         <%= i.hidden_field :saltval, value:0 %>
        
      <% end %>
      <%= f.submit "新規投稿" , class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/foods/wwindex.html.erb
<div class="container">
  <h2>食事を記録する</h2>
  <p>Username:<%= @user.username %>さん</p>
  <% (18..24).each do |n|%>
    <% breakfast = @user.foods.where(when: n).where(which:"breakfast").last %>
    <% lunch = @user.foods.where(when: n).where(which:"lunch").last%>
    <% dinner = @user.foods.where(when: n).where(which:"dinner").last %>
    <p><%= n %>日<%=novdate(n) %></p>
    <div class="row">
      <%if breakfast then %>
        <a class="col-12 col-md-3 btn btn-warning mr-5 mb-3" href="/foods/<%= breakfast.id %>/edit">朝(編集する)</a>
      <%else%>
        <a class="col-12 col-md-3 btn btn-success mr-5 mb-3" href="/foods/<%= n %>/breakfast">朝(新規投稿)</a>
      <% end %>
      <%if lunch then %>
        <a class="col-12 col-md-3 btn btn-warning mr-5 mb-3" href="/foods/<%= lunch.id %>/edit">昼(編集する)</a>
      <%else%>
        <a class="col-12 col-md-3 btn btn-success mr-5 mb-3" href="/foods/<%= n %>/lunch">昼(新規投稿)</a>
      <% end %>
      <%if dinner then %>
        <a class="col-12 col-md-3 btn btn-warning mr-5 mb-3" href="/foods/<%= dinner.id %>/edit">夜(編集する)</a>
      <%else%>
        <a class="col-12 col-md-3 btn btn-success mr-5 mb-3" href="/foods/<%= n %>/dinner">夜(新規投稿)</a>
      <% end %>
    </div>
    <hr>
  <% end %>
</div>

app/views/ingredients/edit.html.erb
<div class="container">
  <h2>Editing a ingredient profile</h2>
  <h2>this is id <%= @ingredient.id %></h2>
  <%= form_for(@ingredient, url:{controller:'ingredients', action:'update'}) do |f| %>
    <div class="form-group pt-3">
      <%= f.label :cal,"カロリー" %>
      <%= f.text_field :cal, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :protein ,"たんぱく質"%>
      <%= f.text_field :protein, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :lipid ,"脂質"%>
      <%= f.text_field :lipid, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :carbon ,"炭水化物"%>
      <%= f.text_field :carbon, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :ca,"カルシウム" %>
      <%= f.text_field :ca, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :fe,"鉄" %>
      <%= f.text_field :fe,{class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :v_a ,"ビタミンA"%>
      <%= f.text_field :v_a, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :v_e ,"ビタミンE"%>
      <%= f.text_field :v_e, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :v_b1,"ビタミンB1" %>
      <%= f.text_field :v_b1, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :v_b2,"ビタミンB2" %>
      <%= f.text_field :v_b2, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :v_c ,"ビタミンC"%>
      <%= f.text_field :v_c, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :fiber,"食物繊維" %>
      <%= f.text_field :fiber, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :fatty ,"飽和脂肪酸"%>
      <%= f.text_field :fatty, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    <div class="form-group pt-3">
      <%= f.label :saltval ,"塩分"%>
      <%= f.text_field :saltval, {class:"form-control", placeholder:"xx cal"} %>
    </div>
    
    <%= f.submit "アップデート" ,class:"btn btn-primary mb-5" %>
    
  <% end %>
  
  
</div>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

<canvas id="myChart" style="position: relative; height:50; width:50"></canvas>
<script>
function drawBackground(target) {
  // 範囲を設定
  var xscale = target.scales["x-axis-0"];
  var yscale = target.scales["y-axis-0"];
  var left = xscale.getPixelForValue(55);  // 塗りつぶしを開始するラベル位置
  var right = xscale.getPixelForValue(65); // 塗りつぶしを終了するラベル位置
  var top = yscale.top;                      // 塗りつぶしの基点（上端）
  
  // 塗りつぶす長方形の設定
  ctx.fillStyle = "rgba(0,255,0,0.3)";
  ctx.fillRect(left, top, right - left, yscale.height);
}
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
  type: 'horizontalBar',
  data: {
    labels: ["<%= @hogehoge %>", "Mathematics", "English", "Social studies", "Science","hoge","hoge","hoge","hoge"],
    datasets: [{
      label: '記録',
      backgroundColor: "rgba(0,0,80,0.4)",
      borderColor: "rgba(0,0,80,1)",
      data: [80, 90, 60, 70, 100, 20, ]
    }, {
      label: '基準値',
      backgroundColor: "rgba(0,255,0,0.4)",
      borderColor: "rgba(0,255,0,1)",
      data: [50, 50, 50, 50, 50, 50, 50, 50, 50]
    }]
  },
  plugins: [{
      beforeDraw: drawBackground // ★
  }],
});
</script>
  <div class="container">
    <p>hogehoge</p>

    <div class="canvas-wrapper">
      <canvas id="chart"></canvas>
    </div>
  </div>
<script>
function drawBackground(target) {
  // 範囲を設定
  var xscale = target.scales["x-axis-0"];
  var yscale = target.scales["y-axis-0"];
  var left = xscale.getPixelForValue(55);  // 塗りつぶしを開始するラベル位置
  var right = xscale.getPixelForValue(65); // 塗りつぶしを終了するラベル位置
  var top = yscale.top;                      // 塗りつぶしの基点（上端）
  
  // 塗りつぶす長方形の設定
  ctx2.fillStyle = "rgba(0,255,0,0.3)";
  ctx2.fillRect(left, top, right - left, yscale.height);
}

// グラフ描画
var ctx2 = document.getElementById('chart').getContext('2d');
var chart = new Chart(ctx2, {
  type: 'horizontalBar',
  data: {
    labels: ["<%= @hogehoge %>","鉄","",""],
    datasets: [{
      data: [<%=@hogenum %>, 0, 30, 92],
    }],
  },
  options: {
    animation: false,
  },
  plugins: [{
      beforeDraw: drawBackground // ★
  }],
});
</script>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "NoRooF Pantry", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Home", home_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          食事
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "食事を記録する", foods_wwindex_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "みんなの食事記録を見る", date_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "食事一覧(記録順)", foods_path, class:"dropdown-item" %>
        </div>
      </li>
    <% end %>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> [<%= current_user.username %>]さん
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "自分の食事記録を見る", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "プロフィールを編集する", edit_user_path(current_user), class: "dropdown-item" %>
            <% if current_user.admin? %>
              <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoRooF Pantry</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    </head>

  <body>
  <%= render 'layouts/navigation' %> 
  <%= render 'layouts/messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is the about page..</h1>

app/views/pages/date.html.erb
<div class="container">
  <h2>みんなの食事記録を確認する</h2>
  <%= link_to '18日(木)', "/users/all/18", class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to '19日(金)', "/users/all/19", class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to '20日(土)', "/users/all/20", class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to '21日(日)', "/users/all/21", class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to '22日(月)', "/users/all/22", class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to '23日(火)', "/users/all/23", class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to '24日(水)', "/users/all/24", class: "btn btn-success btn-lg btn-block mb-4" %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h2 class="mb-3 mt-3">Home</h2>
  <a href="/foods/wwindex" role="button" class="btn btn-success btn-lg btn-block mb-4">食事を記録する</a>
  <%= link_to 'みんなの食事記録', "/date", class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to '自分の食事記録を見る', user_path(current_user.id), class: "btn btn-success btn-lg btn-block mb-4" %>
  <%= link_to 'ユーザー一覧', users_path, class: "btn btn-success btn-lg btn-block mb-4" %>
  <a href="/recipi" role="button" class="btn btn-success btn-lg btn-block mb-4">週一のおすすめレシピ(23日予定)</a>
</div>

app/views/users/index.html.erb
<div class="container">
<h2>this is index page</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Username</th>
        <th scope="col">権限</th>
        <th scope="col">Handle</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.id %></th>
          
          <td><%= link_to user.username,user_path(user) %></td>
          <td><%= userstatus(user) %></td>
          <td>
          <% if user.id==current_user.id %>
            <%= link_to 'Edit', edit_user_path(user) %>
          <% end %>
          <% if current_user.admin? %>
            <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Are you sure?" }%>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>